### PR TITLE
Single Cell Atlas validator

### PR DESCRIPTION
**Pull request by anjaf**
Checks to run on MAGE-TAB metadata files before loading an experiment into Single Cell Expression Atlas. The checks are mainly covering the pre-validation by https://github.com/ebi-gene-expression-group/scxa-control-workflow/blob/master/bin/sdrfToNfConf.R in order to guarantee correct processing.

### CODE REVIEW

**Review by pinin4fjords — APPROVED** [review]
Nice work @anjaf - we've been needing this for a while, sorry I didn't contribute.

Since it's not prod code yet and there's quite a bit of new code I'm just going to approve. But will be nice to have somewhere to PR additional checks to when something goes wrong in analysis!

**Review by hewgreen — APPROVED** [review]
Looks like a great bit of kit. I'll be actually using this soon so I'll give more feedback then.

I like how you are writing it as a library. I think it might be worth making it pip installable so we can run the validator from other things we write.

The validation config is great.

The experiment type flags are great. Be nice if it could infer the experiment type too.

Is it worth some docs on the validator itself? I was wondering what it checks, what it doesn't and if this is a full replacement for other validators we have installed in various places. I'd love to work towards one go to validator.

I also wondered if there was an overall output that gave me a solid Pass/Fail or how I figure it out. I'm thinking about when this is tied into automated runs and fails need to trigger next steps in Jenkins.

**Comment by anjaf** [comment]
@pinin4fjords Thanks, Jon! I am happy for you to contribute directly if you detect any future fails in spite of validation. Or let me know about the problems and I'll add the checks.

**Comment by anjaf** [comment]
@hewgreen 
> The experiment type flags are great. Be nice if it could infer the experiment type too.

The script does actually infer the experiment type, the flags are optional, to be used in case the guessing goes wrong. 

> Is it worth some docs on the validator itself? I was wondering what it checks, what it doesn't and if this is a full replacement for other validators we have installed in various places. I'd love to work towards one go to validator.

Absolutely. I will add some documentation! 
The `magetab_validation.py` script can perform three different check set right now: (1) Pre-MAGE-TAB checks in order to correctly parse the MAGE-TAB into the data model, (2) Annotare type ArrayExpress submission checks on the metadata in the common data model and (3) the SC Atlas checker, which is working directly off the MAGE-TAB (as the data model isn't supporting  the Atlas comments that curators add manually).

> I also wondered if there was an overall output that gave me a solid Pass/Fail or how I figure it out. I'm thinking about when this is tied into automated runs and fails need to trigger next steps in Jenkins.

Yes, the logging part isn't ready yet. This is on my mind and something that I wanted to discuss with you, before implementing. We probably need some error codes and a log that can be easily parsed. Maybe you already have something in mind?

**Comment by pinin4fjords** [comment]
We could have a Conda package as well- would make it easy to integrate into our workflows. If it's on Pip I can do that trivially.

**Comment by pinin4fjords** [comment]
Would it be a crazy idea to have MAGE-TABs in a private GitHub repo with this code running as CI? Matt and Silvie collaborating on SDRF edits made me think of it this morning...

**Comment by hewgreen** [comment]
We should absolutely do this. Need to make a plan fo how we could do it though. Would it open up other opportunities to push files? Because that would be amazing.

**Comment by hewgreen** [comment]
Could add git hooks to run the tracker then so it was always up to date.

**Comment by pinin4fjords** [comment]
Do you think it would work @anjaf ?

**Comment by anjaf** [comment]
Interesting idea! I don't see lots that would stop us. Would want to discuss with curators first, but we should definitely consider it. 
Regarding the packaging and CI, I am thinking if the Atlas validator should actually be a separate repository because it is not directly related to the USI submissions validation and it would be nice to have an independently installable package. 
As for running the script before pushing files, this would be currently be fine because there are no dependencies. We would only need to think what other checks we need and if they are all independent of the Atlas setup.

**Comment by hewgreen** [comment]
Ace.

Separate repo for this makes sense to me.

**Pull request closed without merging**
